In [1]:
import pickle

In [2]:
X = pickle.load(open('X.pkl', 'rb'))
y = pickle.load(open('y.pkl', 'rb'))


In [3]:
X

array([[[185, 186, 187, ..., 216, 215, 216],
        [189, 189, 191, ..., 220, 221, 221],
        [194, 194, 195, ..., 226, 226, 225],
        ...,
        [199, 158,  80, ...,  91,  39,  55],
        [200, 106, 213, ..., 120, 169,  17],
        [144,  73, 211, ..., 166,  18,  23]],

       [[181, 254, 255, ...,  79,  67,  47],
        [239, 253, 253, ..., 121, 121, 122],
        [137, 246, 255, ..., 137, 138, 139],
        ...,
        [ 82,  93,  50, ...,  67,  70,  34],
        [ 49,  93,  79, ...,  69,  57,  54],
        [ 91,  89, 110, ...,  46,  41,  58]],

       [[  1,   2,  21, ..., 203, 203, 204],
        [ 16,   9,   9, ..., 205, 204, 204],
        [ 10,  26,   3, ..., 203, 205, 206],
        ...,
        [120, 126, 134, ...,  71, 128, 154],
        [131, 132, 139, ...,  88, 136,  77],
        [140, 140, 134, ..., 128,  75,  57]],

       ...,

       [[203, 207, 184, ...,  42,  61,  38],
        [ 95,  97,  70, ...,  51,  41,  46],
        [115,  60,  75, ...,  50,  71,  43

In [4]:
y

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,

In [5]:
X = X/255

In [6]:
X

array([[[0.7254902 , 0.72941176, 0.73333333, ..., 0.84705882,
         0.84313725, 0.84705882],
        [0.74117647, 0.74117647, 0.74901961, ..., 0.8627451 ,
         0.86666667, 0.86666667],
        [0.76078431, 0.76078431, 0.76470588, ..., 0.88627451,
         0.88627451, 0.88235294],
        ...,
        [0.78039216, 0.61960784, 0.31372549, ..., 0.35686275,
         0.15294118, 0.21568627],
        [0.78431373, 0.41568627, 0.83529412, ..., 0.47058824,
         0.6627451 , 0.06666667],
        [0.56470588, 0.28627451, 0.82745098, ..., 0.65098039,
         0.07058824, 0.09019608]],

       [[0.70980392, 0.99607843, 1.        , ..., 0.30980392,
         0.2627451 , 0.18431373],
        [0.9372549 , 0.99215686, 0.99215686, ..., 0.4745098 ,
         0.4745098 , 0.47843137],
        [0.5372549 , 0.96470588, 1.        , ..., 0.5372549 ,
         0.54117647, 0.54509804],
        ...,
        [0.32156863, 0.36470588, 0.19607843, ..., 0.2627451 ,
         0.2745098 , 0.13333333],
        [0.1

In [7]:
X = X.reshape(-1, 60, 60, 1)

In [9]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Dense, Flatten

In [14]:
model = Sequential()

model.add(Conv2D(64, (3,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))

model.add(Conv2D(64, (3,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))

model.add(Flatten())

model.add(Dense(128, input_shape = X.shape[1:], activation = 'relu'))

model.add(Dense(2, activation = 'softmax'))

In [15]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [16]:
model.fit(X, y, epochs=5, validation_split=0.1)

Train on 627 samples, validate on 70 samples
Epoch 1/5
627/627 [==============================] - 3s 4ms/sample - loss: 0.7174 - acc: 0.5183 - val_loss: 0.6823 - val_acc: 0.6857
Epoch 2/5
627/627 [==============================] - 3s 4ms/sample - loss: 0.6332 - acc: 0.6842 - val_loss: 0.7226 - val_acc: 0.6429
Epoch 3/5
627/627 [==============================] - 3s 4ms/sample - loss: 0.5252 - acc: 0.7384 - val_loss: 0.6879 - val_acc: 0.7143
Epoch 4/5
627/627 [==============================] - 3s 4ms/sample - loss: 0.4811 - acc: 0.7767 - val_loss: 0.6262 - val_acc: 0.7429
Epoch 5/5
627/627 [==============================] - 3s 4ms/sample - loss: 0.3870 - acc: 0.8309 - val_loss: 0.5035 - val_acc: 0.7857


In [17]:
X.shape

(697, 60, 60, 1)

In [18]:
import time

time.time()

1618135548.1792533

In [ ]:

type(1618135548.1792533)